module.exports = [
  {
    light: {
      "color-scheme": "brad",
      primary: "#f495c1",
      "primary-content": "#ffffff",
      secondary: "#a3c9ff",
      "secondary-content": "#ffffff",
      accent: "#b5ead7",
      "accent-content": "#ffffff",
      neutral: "#6b7280",
      "neutral-content": "#f8fafc",
      "base-100": "#fff8fc",
      "base-200": "#fff1f8",
      "base-300": "#fce7f3",
      "base-content": "#3f3f46",
    },
  },
  {
    dark: {
      "color-scheme": "dark",
      primary: "#f4a9d8",
      "primary-content": "#ffffff",
      secondary: "#89b4fa",
      "secondary-content": "#ffffff",
      accent: "#9fe6cf",
      "accent-content": "#ffffff",
      neutral: "#303446",
      "neutral-content": "#d7dae2",
      "base-100": "#1f2230",
      "base-200": "#191c28",
      "base-300": "#141722",
      "base-content": "#eceef5",
    },
  },
  {
    "coral-pink": {
      "color-scheme": "light",
      primary: "#ef7ea4",
      "primary-content": "#ffffff",
      secondary: "#f8b8ca",
      "secondary-content": "#ffffff",
      accent: "#ffd9e4",
      "accent-content": "#ffffff",
      neutral: "#4a2f34",
      "neutral-content": "#fce8ec",
      "base-100": "#fff7fa",
      "base-200": "#fff0f5",
      "base-300": "#ffd9e4",
      "base-content": "#4a2f34",
    },
  },
  {
    "sea-green": {
      "color-scheme": "light",
      primary: "#4cbfa3",
      "primary-content": "#ffffff",
      secondary: "#8ed8c4",
      "secondary-content": "#ffffff",
      accent: "#d2f3e9",
      "accent-content": "#ffffff",
      neutral: "#153c34",
      "neutral-content": "#e8f7f3",
      "base-100": "#f5fdfb",
      "base-200": "#e9faf4",
      "base-300": "#d2f3e9",
      "base-content": "#153c34",
    },
  },
  {
    "light-blue": {
      "color-scheme": "light",
      primary: "#7aaef7",
      "primary-content": "#ffffff",
      secondary: "#a6c9fb",
      "secondary-content": "#ffffff",
      accent: "#dcecff",
      "accent-content": "#ffffff",
      neutral: "#1f3550",
      "neutral-content": "#e8f1fc",
      "base-100": "#f5f9ff",
      "base-200": "#edf4ff",
      "base-300": "#dcecff",
      "base-content": "#1f3550",
    },
  },
];
